#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2025 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/020-holomorph/uebungsaufgaben/201.tex			\
	chapters/020-holomorph/uebungsaufgaben/202.tex			\
	chapters/020-holomorph/uebungsaufgaben/203.tex			\
	chapters/020-holomorph/1-holomorph.tex				\
	chapters/020-holomorph/2-funktionen.tex				\
	chapters/020-holomorph/3-nichtholomorph.tex			\
	chapters/020-holomorph/chapter.tex

